Update main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -106,12 +106,14 @@ jobs:
             "cpu": 256,
             "essential": true,
             "portMappings": [{"containerPort": 8080}]
-          }]' \ > task-def.json --query 'taskDefinition.taskDefinitionArn' --output text)
-        if [ -z "$TASK_DEF_ARN" ]; then
-          echo "Task definition registration failed!" >&2
+          }]' \
+          --query 'taskDefinition.taskDefinitionArn' --output text)
+
+          if [ -z "$TASK_DEF_ARN" ]; then
+           echo "Task definition registration failed!" >&2
           exit 1
-        fi
-        echo "taskDefinitionArn=$TASK_DEF_ARN" >> "$GITHUB_OUTPUT"
+          fi
+           echo "taskDefinitionArn=$TASK_DEF_ARN" >> "$GITHUB_OUTPUT"
 
     - name: Deploy Amazon ECS task definition
       uses: aws-actions/amazon-ecs-deploy-task-definition@v2
